from sqlalchemy.orm import Session # represents current database session
from sqlalchemy import select
# SQLA 2.0 style 
# SELECT * FROM users; becomes select(User)
# select(User).where(User.email == "abc@gmail.com")
from app.models.user import User
from app.core.security import hash_password, password_needs_rehash, verify_password
from app.core.config import GOOGLE_ALLOWED_EMAIL_DOMAIN
from app.schemas.user import UserCreate
from app.enums.role import UserRole
from app.services.google_auth import verify_google_id_token
from uuid import UUID
from fastapi import HTTPException, status
from sqlalchemy.exc import SQLAlchemyError


def get_user_by_email(
    db: Session,
    email: str,
) -> User | None:
    
    # building query
    statement = select(User).where(
        User.email == email
    )
    result = db.execute(statement)
    # this is like run button for pgAdmin - this sql query is sent to PSQL
    user = result.scalar_one_or_none()
    # since email is UNIQUE there can be 0 or 1 matching user
    return user # we use this in auth register router

# create user service
def create_user(
    db: Session,
    user_data: UserCreate
):
    existing_user = get_user_by_email(
        db,
        user_data.email,
    )

    if existing_user:
        raise HTTPException(
            status_code=409,
            detail="Email already registered.",
        )
    # hash password
    # print(user_data.password)
    # print(len(user_data.password))
    hashed_password = hash_password(
        user_data.password
    )
    # create sqlalchemy object
    new_user = User(
        full_name=user_data.full_name,
        email=user_data.email,
        password_hash=hashed_password,
        roll_number=user_data.roll_number,
        branch=user_data.branch,
        year=user_data.year
    )
    
    db.add(new_user) # this doesn't save user in psql jst tells sqla to track this obj
    # db.commit() # now psql permanently stores the row
    try:
        db.commit()
    except SQLAlchemyError:
        db.rollback()
        raise
    db.refresh(new_user) # updates python obj with values generated by the database such as uuid, created_at, updated_at
    return new_user

def authenticate_user(
    db: Session,
    email: str,
    password: str
):
    user = get_user_by_email(db, email)

    if not user:
        return None

    if not user.password_hash:
        return None

    if not verify_password(password, user.password_hash):
        return None

    if password_needs_rehash(user.password_hash):
        user.password_hash = hash_password(password)
        try:
            db.commit()
            db.refresh(user)
        except SQLAlchemyError:
            db.rollback()

    return user

def assert_allowed_email_domain(email: str) -> None:
    if not GOOGLE_ALLOWED_EMAIL_DOMAIN:
        return

    domain = email.strip().lower().split("@")[-1]
    if domain != GOOGLE_ALLOWED_EMAIL_DOMAIN:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Only @{GOOGLE_ALLOWED_EMAIL_DOMAIN} email addresses can sign in.",
        )


def get_user_by_google_id(db: Session, google_id: str) -> User | None:
    statement = select(User).where(User.google_id == google_id)
    return db.execute(statement).scalar_one_or_none()


def authenticate_google_user(db: Session, id_token: str) -> User:
    payload = verify_google_id_token(id_token)

    email = str(payload["email"]).strip().lower()
    google_id = str(payload["sub"])
    full_name = str(payload.get("name") or email.split("@")[0])
    picture = payload.get("picture")

    assert_allowed_email_domain(email)

    user = get_user_by_google_id(db, google_id)
    if user:
        if user.email != email:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Google account email does not match our records.",
            )
        return user

    user = get_user_by_email(db, email)
    if user:
        if user.google_id and user.google_id != google_id:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="This email is linked to a different Google account.",
            )
        user.google_id = google_id
        user.is_verified = True
        if picture and not user.profile_image:
            user.profile_image = picture
        try:
            db.commit()
            db.refresh(user)
        except SQLAlchemyError:
            db.rollback()
            raise
        return user

    new_user = User(
        full_name=full_name[:100],
        email=email,
        google_id=google_id,
        password_hash=None,
        roll_number=None,
        branch="TBD",
        year=1,
        profile_image=picture,
        is_verified=True,
    )
    db.add(new_user)
    try:
        db.commit()
    except SQLAlchemyError:
        db.rollback()
        raise
    db.refresh(new_user)
    return new_user

# for admin
def get_all_users(db: Session):
    result = db.execute(select(User))
    return result.scalars().all()

# def update_user_role(
#     db: Session,
#     # user_id: int,
#     user_id: UUID,
#     role: UserRole
# ):
#     user = db.select(User).filter(
#         User.id == user_id
#     ).first()
#     # SELECT *
#     # FROM users
#     # WHERE id = ?
#     # LIMIT 1;
#         # if user doesn't exist
#     if not user:
#         return None
#     # update role
#     # user.role = role
#     user.role = role.value # bcz of Enum
#     # UPDATE users
#     # SET role='club_head'
#     # WHERE id=1;
#     # save
#     try:
#         db.commit()
#     except:
#         db.rollback()
#         raise
#     db.refresh(user)

#     return user

def update_user_role(
    db: Session,
    user_id: UUID,
    role: UserRole,
):
    statement = select(User).where(User.id == user_id)
    result = db.execute(statement)
    user = result.scalar_one_or_none()

    if not user:
        return None

    user.role = role.value

    try:
        db.commit()
    except SQLAlchemyError:
        db.rollback()
        raise
    db.refresh(user)
    return user