from sqlalchemy.orm import Session # represents current database session
from sqlalchemy import select
# SQLA 2.0 style 
# SELECT * FROM users; becomes select(User)
# select(User).where(User.email == "abc@gmail.com")
from app.models.user import User
from app.core.security import hash_password, verify_password
from app.schemas.user import UserCreate, UserRole
from uuid import UUID


def get_user_by_email(
    db: Session,
    email: str
):
    # building query
    statement = select(User).where(
        User.email == email
    )
    result = db.execute(statement)
    # this is like run button for pgAdmin - this sql query is sent to PSQL
    user = result.scalar_one_or_none()
    # since email is UNIQUE there can be 0 or 1 matching user
    return user # we use this in auth register router

# create user service
def create_user(
    db: Session,
    user_data: UserCreate
):
    # hash password
    print(user_data.password)
    print(len(user_data.password))
    hashed_password = hash_password(
        user_data.password
    )
    # create sqlalchemy object
    new_user = User(
        full_name=user_data.full_name,
        email=user_data.email,
        password_hash=hashed_password,
        roll_number=user_data.roll_number,
        branch=user_data.branch,
        year=user_data.year
    )
    
    db.add(new_user) # this doesn't save user in psql jst tells sqla to track this obj
    db.commit() # now psql permanently stores the row
    db.refresh(new_user) # updates python obj with values generated by the database such as uuid, created_at, updated_at
    return new_user

def authenticate_user(
    db: Session,
    email: str,
    password: str
):
    user = get_user_by_email(db, email)

    if not user:
        return None

    if not verify_password(password, user.password_hash):
        return None

    return user

# for admin
def get_all_users(db: Session):
    return db.query(User).all()

def update_user_role(
    db: Session,
    # user_id: int,
    user_id: UUID,
    role: UserRole
):
    user = db.query(User).filter(
        User.id == user_id
    ).first()
    # SELECT *
    # FROM users
    # WHERE id = ?
    # LIMIT 1;
        # if user doesn't exist
    if not user:
        return None
    # update role
    # user.role = role
    user.role = role.value # bcz of Enum
    # UPDATE users
    # SET role='club_head'
    # WHERE id=1;
    # save
    db.commit()
    db.refresh(user)

    return user