from enum import Enum


class NotificationType(str, Enum):
    EVENT_REGISTERED = "EVENT_REGISTERED"
    APPLICATION_RECEIVED = "APPLICATION_RECEIVED"
    APPLICATION_APPROVED = "APPLICATION_APPROVED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    MARKETPLACE_INQUIRY = "MARKETPLACE_INQUIRY"
    SYSTEM = "SYSTEM"
