"""create pyqs table

Revision ID: 026399c75220
Revises: f92cabafd7ef
Create Date: 2026-07-28 14:25:00.390487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026399c75220'
down_revision: Union[str, Sequence[str], None] = 'f92cabafd7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.Enum('CSE', 'ECE', 'EEE', 'ME', 'CE', 'CHE', name='branch'), nullable=False),
    sa.Column('semester', sa.Enum('SEM1', 'SEM2', 'SEM3', 'SEM4', 'SEM5', 'SEM6', 'SEM7', 'SEM8', name='semester'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyqs')
    # ### end Alembic commands ###
