"""create marketplace items table

Revision ID: 2db9b5641227
Revises: b9b5f50bf168
Create Date: 2026-07-28 10:05:33.702246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db9b5641227'
down_revision: Union[str, Sequence[str], None] = 'b9b5f50bf168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('BOOKS', 'ELECTRONICS', 'FURNITURE', 'STATIONERY', 'CLOTHING', 'SPORTS', 'OTHERS', name='itemcategory'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', name='itemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    sa.Column(
        "status",
        sa.Enum("AVAILABLE", "SOLD", name="itemstatus"),
        nullable=False,
        server_default="AVAILABLE",
    ),
    sa.CheckConstraint(
        "price >= 0",
        name="ck_marketplace_price",
    ),
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplace_items')
    # ### end Alembic commands ###
