"""create resume builder tables

Revision ID: 31a0d90b9b98
Revises: ee0da2ba511a
Create Date: 2026-07-29 09:55:06.562034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31a0d90b9b98'
down_revision: Union[str, Sequence[str], None] = 'ee0da2ba511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions_of_responsibility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievements', sa.Column('achievement_url', sa.String(), nullable=True))
    op.alter_column('certifications', 'credential_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('educations', sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.alter_column('educations', 'branch',
               existing_type=postgresql.ENUM('CSE', 'ECE', 'EEE', 'ME', 'CE', 'CHE', name='branch'),
               nullable=True)
    op.drop_column('educations', 'cgpa')
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.add_column('educations', sa.Column('cgpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.alter_column('educations', 'branch',
               existing_type=postgresql.ENUM('CSE', 'ECE', 'EEE', 'ME', 'CE', 'CHE', name='branch'),
               nullable=False)
    op.drop_column('educations', 'score')
    op.alter_column('certifications', 'credential_id',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('achievements', 'achievement_url')
    op.drop_table('positions_of_responsibility')
    # ### end Alembic commands ###
