"""create recruitment drives and club applications tables

Revision ID: 4a796bc619f5
Revises: 1d1149ac47b7
Create Date: 2026-07-26 22:37:31.491687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a796bc619f5'
down_revision: Union[str, Sequence[str], None] = '1d1149ac47b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_drives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_start', sa.DateTime(), nullable=False),
    sa.Column('application_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='recruitmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'title', name='uq_club_recruitment_title')
    )
    op.create_table('club_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('recruitment_drive_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['recruitment_drive_id'], ['recruitment_drives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'club_id', name='uq_user_club_application')
    )
    op.drop_column('clubs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_table('club_applications')
    op.drop_table('recruitment_drives')
    # ### end Alembic commands ###
