"""cleanup club and application schema

Revision ID: 85e844892444
Revises: 4a796bc619f5
Create Date: 2026-07-26 22:46:45.754627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e844892444'
down_revision: Union[str, Sequence[str], None] = '4a796bc619f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_club_application'), 'club_applications', type_='unique')
    op.create_unique_constraint('uq_user_recruitment_application', 'club_applications', ['user_id', 'recruitment_drive_id'])
    op.add_column('clubs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clubs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('clubs_head_id_fkey'), 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'head_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('head_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('clubs_head_id_fkey'), 'clubs', 'users', ['head_id'], ['id'])
    op.alter_column('clubs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('clubs', 'created_at')
    op.drop_constraint('uq_user_recruitment_application', 'club_applications', type_='unique')
    op.create_unique_constraint(op.f('uq_user_club_application'), 'club_applications', ['user_id', 'club_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
