"""create placement experiences table

Revision ID: b9b5f50bf168
Revises: 9d0db521b02a
Create Date: 2026-07-28 09:28:30.302855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b5f50bf168'
down_revision: Union[str, Sequence[str], None] = '9d0db521b02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.Enum('INTERNSHIP', 'FULL_TIME', name='jobtype'), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('ctc', sa.Float(), nullable=True),
    sa.Column('stipend', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('interview_rounds', sa.Text(), nullable=False),
    sa.Column('preparation', sa.Text(), nullable=False),
    sa.Column('experience', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        "cgpa >= 0 AND cgpa <= 10",
        name="ck_placement_cgpa",
    ),

    sa.CheckConstraint(
        "year >= 2000",
        name="ck_placement_year",
    ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_experiences')
    # ### end Alembic commands ###
