"""add pdf_path to resumes

Revision ID: d3409b136514
Revises: 3c0c050f696a
Create Date: 2026-07-29 22:41:42.046010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3409b136514'
down_revision: Union[str, Sequence[str], None] = '3c0c050f696a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'pdf_path')
    # ### end Alembic commands ###
