"""change password_hash to text

Revision ID: dbdc53eedc13
Revises: e27449b906ca
Create Date: 2026-07-25 12:19:26.887105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdc53eedc13'
down_revision: Union[str, Sequence[str], None] = 'e27449b906ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=False)
    op.drop_constraint(op.f('users_password_hash_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_password_hash_key'), 'users', ['password_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
