"""create lost found items table

Revision ID: f92cabafd7ef
Revises: 2db9b5641227
Create Date: 2026-07-28 14:06:06.524058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92cabafd7ef'
down_revision: Union[str, Sequence[str], None] = '2db9b5641227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_found_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('LOST', 'FOUND', name='lostfoundtype'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column(
        "status",
        sa.Enum("OPEN", "CLAIMED", name="lostfoundstatus"),
        nullable=False,
        server_default="OPEN",
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(title) >= 2', name='ck_lost_found_title_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lost_found_items')
    # ### end Alembic commands ###
